### ISSUE TITLE
Two "piped.video" instances

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/libredirect#652] opened 2023-03-07 11:21 UTC
The instance list has two occurrences of this URL. The first one works. The 2nd one, which is at the bottom, doesn't.

Edit: by "works", I mean that if you try to add it to your favourite instances, it doesn't work. Clicking on the plus sign next to the 2nd instance doesn't do anything at all. Trying to add the 1st one works.

**Comment by IkelAtomig** [comment] 2023-03-07 13:22
It's because of due to the official Instance hosting Cloudflare based one and Non-Cloudflare based one.

**Comment by ManeraKai** [comment] 2023-03-07 13:36
duplicate of: https://github.com/libredirect/libredirect/issues/614

**Closed** 2023-03-07 15:13 UTC
