### ISSUE TITLE
Leak: LibRedirect allows through <embed> tags

### ISSUE THREAD

**Issue by ndren** [libredirect/libredirect#575] opened 2022-12-26 19:14 UTC
Take a look at [this jsfiddle](https://jsfiddle.net/5q0ans92/1/) (warning: connects to youtube.com).

To reproduce: `<embed src="https://www.youtube.com/embed/dQw4w9WgXcQ">`

Libredirect does not handle embed tags, leading to a privacy leak.

**Comment by ManeraKai** [comment] 2023-01-07 07:17
Duplicate of https://github.com/libredirect/libredirect/issues/541

**Comment by ndren** [comment] 2023-01-07 22:09
@ManeraKai Please reopen the issue.

If it is impossible to use Invidious, I do not want it to connect to YouTube. I would like the option for it to not connect at all in that case.

I am happy for that to be opt-in, just like all the other settings, but I do not agree with the current privacy impact.

**Comment by ManeraKai** [comment] 2023-01-07 22:11
> I would like the option for it to not connect at all in that case.

That is logical. ok

**Closed** 2023-02-08 23:18 UTC
Labels: enhancement
