### ISSUE TITLE
Chrome is actively blocking LibRedirect

### ISSUE THREAD

**Issue by FuccDucc** [libredirect/libredirect#554] opened 2022-11-27 09:27 UTC
Google Chrome is undertaking the following actions to frustrate deploying LibRedirect:

1) It removes the download, despite clicking on "**Continue download**" like this:
![image](https://user-images.githubusercontent.com/61570793/204127758-76c02f9a-0e40-4205-b5a5-674bec89a48a.png)

![image](https://user-images.githubusercontent.com/61570793/204127805-9eadea35-4115-4df2-85d4-5b66989b224e.png)

The result of allowing the download anyways is Chrome pretending it has successfully downloaded it:
![image](https://user-images.githubusercontent.com/61570793/204127857-f97ed95f-a433-4660-9517-0e134681d7c0.png)

But there is no file in the destination folder "Downloads", at all, no matter repeatedly trying. At this moment of the purported download succeeding, this error shows up below URL bar:
![image](https://user-images.githubusercontent.com/61570793/204127892-06793a56-8b3c-4436-b29e-c07e19afac9a.png)
it says **Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'**

So, i managed to download a palpable .crx file to my PC anyways, by selecting 'Desktop' folder instead of Downloads. But the chain of Chrome's deliberate blocking/breaking of this extension doesn't stop there.

Because once installed using the chrome://extensions page, in dev mode, the "Enable" button for the extension is **greyed out**
As seen below:
![image](https://user-images.githubusercontent.com/61570793/204127984-86b6caa7-e178-4fd4-9cd3-6b7d05806771.png)

Left greyed out extensions are for reference of how a non-greyed out "Enable" button looks like. Due to being greyed out, the extension can't be used, as it cannot be enabled and Chrome has already decided that it's disabled right after installing the extension.

I am on Chrome Canary 110.0.5443.0, but it shouldn't matter, its my daily driver and i never experience add-on compatibility issues. Someone else can test it with other Chrome versions, and at most it can be a sign that Google is preparing technical measures to break privacy plugins like LibRedirect (in development), but again i would expect equal results.

It should always be the user's decision which plugin to launch, so can you think of a reason (or workaround) for the "Enable" toggle to get fixed and let me turn on LibRedirect in Chrome? I'm using Firefox as side browser but would also like to use it in Chrome.

**Comment by whyjxz14** [comment] 2022-11-27 18:48
well,I does from long ago,you cannot install uncertified crx anymore on chrome,not aim to  privacy plugins,just
follow the installtion instruction they provide to install with zip:
https://github.com/libredirect/libredirect/blob/master/chromium.md

**Comment by eightyy8** [comment] 2022-11-27 22:22
Horrible. But their is a fix, follow the link below and click download.
https://www.mozilla.org
Hope this helps.

**Comment by AlyoshaVasilieva** [comment] 2022-11-28 03:55
Set up Chrome group policy settings and add `oladmjdebphlnjjcnomfhhbfdldiimaf` to extension installation allow list, I think that fixes it (for now)

Or use Firefox

**Comment by IkelAtomig** [comment] 2022-12-07 02:44
Duplicate of #415

**Closed** 2022-12-07 09:15 UTC
