### ISSUE TITLE
[Suggestion] Add gothub

### ISSUE THREAD

**Issue by TheHolyTachanka** [libredirect/libredirect#638] opened 2023-02-23 16:35 UTC
Basically the title
Its an "Alternative front-end for GitHub written with Go."
Here is their repo
https://codeberg.org/gothub/gothub

**Comment by ManeraKai** [comment] 2023-02-23 18:58
Duplicate of :https://github.com/libredirect/libredirect/issues/630

We already added it, wait for the next release :)

**Closed by ManeraKai** 2023-02-23 18:58 UTC

**Comment by TheHolyTachanka** [comment] 2023-02-23 18:59
> We already added it, wait for the next release :)
> 
> Duplicate of: #630

Cool, srry for the issue then and thank you for making this
