### ISSUE TITLE
FreeTube not working

### ISSUE THREAD

**Issue by PAI5REECHO** [libredirect/libredirect#617] opened 2023-02-04 21:13 UTC
When opening `https://www.youtube.com/watch?v=Hg6L_7qLIEQ` in my browser nothing happens:
![image](https://user-images.githubusercontent.com/96688573/216789798-7091d6a5-a00b-43aa-9e46-66e131753b60.png)

When opening `freetube://https://www.youtube.com/watch?v=Hg6L_7qLIEQ` it opens in FreeTube. This seems like a browser extension issue.

**Comment by ManeraKai** [comment] 2023-02-05 05:57
Duplicate of issue: https://codeberg.org/LibRedirect/libredirect/issues/72

Fixed this don't worry

**Closed by ManeraKai** 2023-02-05 05:57 UTC
