### ISSUE TITLE
en.wikipedia.org doesn't redirect to any wikiless instances.

### ISSUE THREAD

**Issue by amogusussy** [libredirect/libredirect#399] opened 2022-07-26 20:46 UTC
Wikipedia redirects all links to links with your language in the URL, stopping this extension from redirecting you to wikiless.
For example, if you wanted to go to https://www.wikipedia.org/wiki/ThinkPad, it would redirect you to https://en.wikipedia.org/wiki/ThinkPad. Which stops the extension from detecting it as a wikipedia link.
Could you make it so that all.wikipedia.org redirects to wikiless? Thank you.

**Comment by AlyoshaVasilieva** [comment] 2022-07-26 21:22
When I click https://www.wikipedia.org/wiki/ThinkPad it redirects me to https://wikiless.org/wiki/ThinkPad just fine

**Comment by EdwardLangdon** [comment] 2022-07-27 05:52
IIRC, Wikipedia redirects are turned off by default.

**Comment by EdwardLangdon** [comment] 2022-07-27 13:32
You need to manually turn it on for redirection to work. Hope it helps.

**Comment by iwakuraSSBM** [comment] 2022-07-28 11:52
I too am experiencing this issue. I have disabled all other add-ons and extensions and tested it and the issue still persists.

I can confirm that wikipedia.org links are redirecting to en.wikipedia.org (even after deleting all cookies for wikipedia.org) and it appears that this might be causing the issue. I have turned on wikipedia redirects in the libredirect settings and also added the toggle in the pop-up menu, for completion.

**Comment by EdwardLangdon** [comment] 2022-07-28 13:43
@iwakuraSSBM Can you make a screenrecord ?

**Comment by amogusussy** [comment] 2022-07-28 17:48
I've just realized that I've forgot to turn the wikipedia redirection on in the settings.

**Comment by iwakuraSSBM** [comment] 2022-08-02 12:01
> @iwakuraSSBM Can you make a screen capture and put it here ?
![2022-08-02-125555_1907x1034_scrot](https://user-images.githubusercontent.com/95041008/182369231-23a9092f-fd86-4dd4-b1d3-c4ca29b37844.png)

As you can see the page is resolving to en.wikipedia.org but curiously it presents a wikiless icon. uMatrix shows that all the wikiless instances are trying to be loaded but the redirect should happen before this page is ever reached. Here's another shot where libredirect is the only add-on working.
![2022-08-02-125926_1916x601_scrot](https://user-images.githubusercontent.com/95041008/182369735-948e61f7-c724-4374-b848-d6e85d709596.png)

**Comment by iwakuraSSBM** [comment] 2022-08-02 12:04
I was taking a look at assets/javascripts/wikipedia.js and I looks like the regexp is correct it should catch these, but I'm guessing it's more related to how the GETArguments is built? I don't really have the resources to be trying to build this  project myself to troubleshoot.

**Comment by EdwardLangdon** [comment] 2022-08-02 14:37
I am off from LR team. @ManeraKai will assist you.

**Comment by ManeraKai** [comment] 2022-08-02 14:41
Does Disabling the extension completely fix this for you?

**Comment by iwakuraSSBM** [comment] 2022-08-02 23:52
@ManeraKai Both disabling wikipedia in libredit and disabling the extension completely allows wikipedia to load normally.

**Comment by ManeraKai** [comment] 2022-08-03 06:44
It's working for me even in incognito mode. Go to `about:debugging#/runtime/this-firefox` => `Inspect` for LibRedirect.

**Comment by iwakuraSSBM** [comment] 2022-08-03 14:49
Here's the console output, you can see it is trying to redirect all the calls for resources, scripts, css etc but never the main url.
![2022-08-03-154712_1907x946_scrot](https://user-images.githubusercontent.com/95041008/182638845-abe483c3-a199-4bb3-914f-662f8d214ef2.png)

**Comment by ManeraKai** [comment] 2022-08-03 16:11
It's so similar to this one: https://github.com/libredirect/libredirect/issues/110

**Comment by iwakuraSSBM** [comment] 2022-08-08 10:59
I tried to remove all site data related to anything wikipedia or wikiless related and the issue still persists.

**Comment by EdwardLangdon** [comment] 2022-10-15 02:31
@iwakuraSSBM Can you check in v2.3.0 and v2.3.1 (pull from source) ?

**Comment by IkelAtomig** [comment] 2022-11-02 03:01
It seems like using uMatrix is causing this issue. uMatrix is unmaintained. I suggest you to remove it and see if the redirects works.

Better use uBlock Origin in Medium mode alone.

We are closing this issue as it is stale and no reply from author.
Would be great to know if the issue is fixed.

**Closed by IkelAtomig** 2022-11-02 03:01 UTC
