### ISSUE TITLE
Add startpage

### ISSUE THREAD

**Issue by sitiom** [libredirect/libredirect#52] opened 2022-02-20 01:13 UTC
`https://www.startpage.com/do/search?q=%s`

**Comment by ManeraKai** [comment] 2022-02-20 07:31
I've discussed this with @alefvanoon before. It was there and we removed it with many others as it's really not that hard to change the default search engine on your browser. This extension was build to help auto redirecting randomly to decentralized services like SearX and Whoogle after all.

**Comment by sitiom** [comment] 2022-02-20 07:38
> it's really not that hard to change the default search engine on your browser.

I've done that already, but the use case is to redirect google query links to Startpage and the likes.

**Comment by ManeraKai** [comment] 2022-02-20 07:41
SearX supports many search engines. We want to promote just decentralized services too.

**Comment by sitiom** [comment] 2022-02-21 01:02
At least an option would be helpful.

**Comment by ManeraKai** [comment] 2022-02-24 20:41
> I've done that already, but the use case is to redirect google query links to Startpage and the likes.

I'm really thinking of this specific scenario. It's just so rare it's not worth it to add a whole new frontend.

I'm sorry for being strict with adding this. I'm doing this to not clutter up the extension and shift it's main objective that is redirecting to decentralized instances.

**Comment by sitiom** [comment] 2022-02-25 01:15
The alternative would be to have the ability to add a custom frontend, then I would be able to put `https://www.startpage.com/do/search?q=%s` there.

**Comment by ManeraKai** [comment] 2022-02-25 14:47
That would be too complex for a user friendly extension. If you really want startpage. I suggest you use this extension: https://einaregilsson.com/redirector/ It's for custom redirects.

**Comment by sitiom** [comment] 2022-02-25 15:22
Here:
![image](https://user-images.githubusercontent.com/56180050/155740772-e5a8c118-48ac-4674-bf09-7373fefb7c13.png)

The exceptions are set to `https://google.com` and `https://www.google.com` as before.

**Comment by sitiom** [comment] 2022-02-25 15:30
That one seems too complex just for a specific use case. Generally, I would like the experience to be like setting a default search engine but for redirects:
![image](https://user-images.githubusercontent.com/56180050/155741877-22e28a30-f9d6-45b0-8738-863c9f0739d4.png)

In which I can specify my query URL.

**Comment by sitiom** [comment] 2022-02-25 15:42
On second thought, I'll be using Redirector. But if other users might want this feature, feel free to reopen it.

**Comment by ManeraKai** [comment] 2022-02-25 15:47
Adding custom redirects is almost a duplicate of the [redirector](https://einaregilsson.com/redirector/) extension. It will shift away the objective of this extension.

Use this:
Description: `Redirecting google to startpage`
Example URL: `https://www.google.com/search?q=wewe`
Include pattern: `https?:\/\/(www\.|maps\.|search\.|)google\.com(\...|)(\/search\?..*|\/$)`
Redirect to: `https://startpage.com/do$3`
Pattern type: `Regular Expression`

![image](https://user-images.githubusercontent.com/40805353/155744894-c9b9313e-6a8c-43d8-bf3a-1be72e7b777a.png)

**Comment by ManeraKai** [comment] 2022-03-10 06:28
@sitiom When we were adding `pixiv.moe`, it wasn't that privacy friendly. Neither old.reddit.com but sometimes you can't have a better option so we kept them but added a warning that they're not a fully privacy frontend. That's why we'll add startpage to the extension but with a warning message that it's a centralized service 👍

**Comment by ManeraKai** [comment] 2022-03-10 06:29
This is the best way to settle this down since I don't want LibRedirect to fight with people but give them the choice with some warnings.

**Comment by sitiom** [comment] 2022-03-10 06:39
I'm using SearX now but up to you 😅

**Closed** 2022-03-10 07:57 UTC
Labels: enhancement
