### ISSUE TITLE
please add libremdb (IMDB alt)

### ISSUE THREAD

**Issue by deroverda** [libredirect/libredirect#309] opened 2022-06-03 12:28 UTC
A FOSS alternative front-end to IMDb. 

[libremdb](https://libremdb.herokuapp.com/about)

**Comment by ManeraKai** [comment] 2022-06-03 13:16
We'll implement it but after fixing the current bugs and issues.
Duplicate of https://github.com/libredirect/libredirect/issues/230

**Closed by ManeraKai** 2022-06-03 13:16 UTC
