### ISSUE TITLE
LibRedirect settings on Desktop (Firefox) are constantly resetting. 

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#473] opened 2022-10-09 20:10 UTC
OS: Windows 10.

Browser: Firefox (Latest Stable Version)

Ever since updating LibRedirect, I've found every setting I've toggled (including which instances I want to use) is constantly resetting to their pre-update version.

This is frustrating, because I want to use different options because of how much the extension has improved functionally. 

Please Help.

**Comment by heywolf15** [comment] 2022-10-10 01:02
OS: Windows 10.
Browser: Firefox
Same issue

**Comment by EdwardLangdon** [comment] 2022-10-10 02:27
This ain't good. The new version isn't supposed to reset rather migrate it to the new format. We are investigating this.

**Comment by fastcat001** [comment] 2022-10-10 06:04
I have exactly same issue, please resolve and make sure this won't happen again.

**Comment by EdwardLangdon** [comment] 2022-10-10 06:27
This issue isn't caused by us rather something else. If the settings are being reset, There will be prior notice with an option to export settings. We didn't do it.

**Comment by fastcat001** [comment] 2022-10-10 06:30
> This issue isn't caused by us rather something else. If the settings are being reset, There will be prior notice with an option to export settings. We didn't do it.

I reset settings, tried to setup again, but all the changes I made are reset again automatically,
there was not such issue in the previous release.

**Comment by fastcat001** [comment] 2022-10-10 13:28
> That's weird. It isn't the same in Chromium.

What Chromium-based browsers do you use with Libredirect?

**Comment by EdwardLangdon** [comment] 2022-10-10 13:30
Brave Browser

**Comment by fastcat001** [comment] 2022-10-10 13:41
> Brave Browser

I tried it once and its 1GB Massive Installation Folder was full of crypto and wallet junk, even thought I disabled them all

**Comment by EdwardLangdon** [comment] 2022-10-10 14:27
Everybody's perceptions differ.

**Comment by fastcat001** [comment] 2022-10-10 14:40
> Must be a Firefox issue, then. I can reproduce the issue here too.

Always coming back to Firefox, no crypto junk, no chromium, just browser to browse the web

**Comment by xurich-xulaco** [comment] 2022-10-10 21:28
I have the same issue, I tried to circumvent it by exporting my settings and then, when I closed and opened firefox, reload them manually; it resulted on all the default instances being erased and just having empty lists of instances on each setting.
Another problem, the same as resetting instances, is that the popup list is also rested.

**Comment by EdwardLangdon** [comment] 2022-10-11 02:48
> reload them manually;

You mean importing, You don't see the instance lists. But are you still redirected ?

**Comment by MintMain21** [comment] 2022-10-11 03:04
> OS: Fedora 36
> Browser: Firefox
> 
> I have the same issue, 

Interesting, it's not even Windows specific.

**Comment by EdwardLangdon** [comment] 2022-10-11 03:11
It's Firefox Specific then. Hotfix is on its way.

**Comment by EdwardLangdon** [comment] 2022-10-11 15:47
https://codeberg.org/LibRedirect/libredirect/commit/c60e6f2c52196ded91b30db1519239e7a7fdf8d9 - Fix Complete after finishing Issue 475.

Hotfix will be released.

**Comment by meatspinner** [comment] 2022-10-15 22:29
I'm having this issue on Brave too.

**Comment by MintMain21** [comment] 2022-10-16 17:40
@meatspinner Is it fixed?

**Comment by MintMain21** [comment] 2022-10-16 18:45
I haven't tested it enough, but I can confidently say that the settings page still freezes on Android, but that's another issue.

**Comment by heywolf15** [comment] 2022-10-16 23:41
I still have the issue on v. 2.3.1
Why this is being closed without even confirm the user feedback?

**Comment by meatspinner** [comment] 2022-10-17 00:00
> @meatspinner Is it fixed?

Yeah, I tested on both brave and firefox and settings not sticking is still a issue, but you can get them to save by doing what heywolf15 said above, going back and forth between the settings, reloading the settings page, closing and reopening the browser. Its something should be looked into it.

**Comment by MintMain21** [comment] 2022-10-17 05:40
@EdwardLangdon Open this back up please.

**Comment by EdwardLangdon** [comment] 2022-10-18 02:24
Do you have your browsers updated cuz some have browsers lagging behind upstream because of the Distros they use

**Comment by EdwardLangdon** [comment] 2022-10-18 05:19
WHat do you mean by resetting here ?

All settings are reset to default or to the settings you had in v2.2.1 ?

**Comment by heywolf15** [comment] 2022-10-18 15:35
@EdwardLangdon no, I have the latest Firefox. I think resetting the setting doesn't matter because I did try this on the previous version

> going back and forth between the settings, reloading the settings page

But only one instance being saved and really hard to duplicate that again. Now after doing that thing on the latest version, I don't know for how many times, suddenly every change is being saved. I don't know if I can duplicate that or even want to try again

**Comment by EdwardLangdon** [comment] 2022-10-19 01:47
There are latest commits fixing this issue. Download .zip and load the add-on & test it.

**Comment by MF-Debug** [comment] 2022-10-19 08:36
> There are latest commits fixing this issue. Download `.zip` and load the add-on via `about:debugging` & test it. This is the last thing we can do regarding this issue.

I'm sorry but if you are suggesting to build from the source & test it, it's not possible for me. Maybe someone else can do that or I would appreciate if you can attach the file here to do the testing.

**Comment by EdwardLangdon** [comment] 2022-10-19 13:30
@MF-Debug Just download the code as `zip`, Extract it, Make `src` folder as archive again.

Set `xpinstall.signatures.required` to `false` not possible in Stable. Then load the addon from the second zip file you made.

**Comment by MF-Debug** [comment] 2022-10-19 14:22
@EdwardLangdon I've tested the latest commit by making a zip file of the src folder. Unfortunately, it still isn't fixed. :(

**Comment by MF-Debug** [comment] 2022-10-19 15:03
Here you go.
![image](https://user-images.githubusercontent.com/6173607/196729050-038fd4d8-e593-41d7-8374-987fe1ece2b6.png)

**Comment by EdwardLangdon** [comment] 2022-10-19 15:07
Are you able to see this in Stable or Chromium browsers too ?

**Comment by EdwardLangdon** [comment] 2022-10-19 15:22
Can you expand those errors and send a Screenshot ?

It might help a lot in investigating this issue.

**Comment by MF-Debug** [comment] 2022-10-19 15:27
I took the screenshot by already expanding the error to show the complete messages.

**Comment by EdwardLangdon** [comment] 2022-10-20 02:00
Sending a Video will ony be a helpful solution for this issue.

**Comment by heywolf15** [comment] 2022-10-20 05:19
@EdwardLangdon I get the same warning as well. You don't get the warning on your end?

**Comment by EdwardLangdon** [comment] 2022-10-20 05:24
I do get the warning but my settings aren't reset in Firefox. I am sure. My Settings are there as is. Rock solid.

**Comment by EdwardLangdon** [comment] 2022-10-20 14:07
Go to `about:devtools-toolbox?id=7esoorv3%40alefvanoon.anonaddy.me&type=extension`, open the console, and to do it again with the console visible.

if you cannot have them both next to each other, then just take a screenshot of the console after you recorded the video again.

**Comment by MF-Debug** [comment] 2022-10-20 14:27
https://user-images.githubusercontent.com/6173607/196976379-85dd05e8-2239-497d-8a41-e5683381c950.mp4


![image](https://user-images.githubusercontent.com/6173607/196975332-6517da07-ed42-43c9-a922-49b20f5949f8.png)

the console output is empty after my new video.

**Comment by EdwardLangdon** [comment] 2022-10-20 14:45
Weirdest issue ever seen. Can you put your Settings backup file here or mail it to me personally ?

**Closed** 2022-10-20 15:26 UTC
Labels: Reproducible Bug

**Comment by EdwardLangdon** [comment] 2022-10-20 15:28
The Push from codeberg automatically closed the issue.

Can you try again from `src` with the new commit ?

**Comment by MF-Debug** [comment] 2022-10-20 15:35
now everything works perfectly! 🥇

**Comment by EdwardLangdon** [comment] 2022-10-20 15:38
Great to hear. Hotfix will be released as soon as possible.
