### ISSUE TITLE
Remove all alefvanoon.xyz instances

### ISSUE THREAD

**Issue by Victor239** [libredirect/libredirect#305] opened 2022-06-02 11:55 UTC
https://alefvanoon.xyz subdomains are no longer up and domain is for sale.

**Comment by EdwardLangdon** [comment] 2022-06-02 12:00
Duplicate of #294 and #304

**Closed** 2022-06-02 12:00 UTC
Labels: duplicate, invalid, wontfix

**Comment by Victor239** [comment] 2022-06-02 12:02
Ah sorry, didn't realise where instance lists came from.
